# script parameters
model_id: "google/gemma-2-27b-it" # Hugging Face model id
dataset_path: "."                      # path to dataset
max_seq_len:  4096                     # max sequence length for model and packing of the dataset
# training parameters
output_dir: "./gemma_judge_ver0.1"  # Temporary output directory for model checkpoints
report_to: wandb                # report metrics to tensorboard "wandb"
learning_rate: 0.0002                  # learning rate 2e-4
lr_scheduler_type: "cosine"          # learning rate scheduler , # cosine , constant
num_train_epochs: 5                    # number of training epochs
per_device_train_batch_size: 4        # batch size per device during training
per_device_eval_batch_size: 1          # batch size for evaluation
gradient_accumulation_steps: 4         # number of steps before performing a backward/update pass
optim: adamw_torch                     # use torch adamw optimizer
logging_steps: 5                      # log every 10 steps
save_strategy: steps                   # save checkpoint every epoch , epochs, steps
save_steps: 100                   
# evaluation_strategy: epoch             # evaluate every epoch
max_grad_norm: 0.3                     # max gradient norm
warmup_ratio: 0.03                     # warmup ratio
bf16: true                             # use bfloat16 precision
tf32: true                             # use tf32 precision
gradient_checkpointing: false           # use gradient checkpointing to save memory
# neftune_noise_alpha: 5
# FSDP parameters: https://huggingface.co/docs/transformers/main/en/fsdp
fsdp: "full_shard auto_wrap" # remove offload if enough GPU memory
fsdp_config:
  fsdp_auto_wrap_policy: "TRANSFORMER_BASED_WRAP"
  backward_prefetch: "backward_pre"
  forward_prefetch: "false"
  # use_orig_params: "true"
  fsdp_use_orig_params: "true"